### ISSUE TITLE
Segmentation fault 3.01

### ISSUE THREAD

**Issue by CDieterich** [seqan/flexbar#10]
Hello,
while
Flexbar 2.7 works fine:
flexbar -r K002000101_56068_1.fq.gz -a Seq_adp_eCLIP.fa -b Seq_barcode_eCLIP.fa -qf sanger -t flexbar27

Flexbar 3.0.1
flexbar_dev -r K002000101_56068_1.fq.gz -a Seq_adp_eCLIP.fa -b Seq_barcode_eCLIP.fa -qf sanger
Segmentation fault

crashes

Please look into this.

Seq_barcode_eCLIP.fa
>RNA_A01_upstraem_revcomp
CTACACGACGCTCTTCCGATCTAAGCAAT
>RNA_B06_upstream_revcomp
CTACACGACGCTCTTCCGATCTGGCTTGT
>RIL_upstream_revcomp
CACGACGCTCTTCCGATCT

and

>cDNA_3p_adapter
NNNNNAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC

**Comment by jtroehr** [comment]
This issue is resolved in Flexbar 3.0.2
