### ISSUE TITLE
Scoring of adapter alignment looks flawed

### ISSUE THREAD

**Issue by CDieterich** [seqan/flexbar#11]
adapter-trim-end:      RIGHT
adapter-min-overlap:   10
adapter-error-rate:    0.2
adapter-match:         1
adapter-mismatch:     -1
adapter-gap:          -6

--align-log MOD looks fishy

```
Sequence removal: right side
  query id         cDNA_3p_adapter
  query pos        33-72
  read id          K00200:101:HGHKYBBXX:2:1101:19289:1261
  read pos         0-43
  score            6
  overlap          10
  errors           2
  error threshold  2
  remaining read   CGCTCTTCCGATCTGGCTTGNGGACTGCTCTAC
  remaining qual   FFJJAJFFFFFJ7JJF<JFF#JJJFFJJJFJJA

  Alignment:

      0     .    :    .    :    .    :    .    :    .    : 
        CGCTCTTCCGATCTGGCTTGNGGACTGCTCTACTGAATACAAC-------
                                              | | |       
        ---------------------------------NNNNNAGATCGGAAGAG

     50     .    :    .    :   
        ----------------------
```

**Comment by CDieterich** [comment]
If I take away the leading Ns, it looks good
`Sequence removal: right side
  query id         cDNA_3p_adapter
  query pos        34-68
  read id          K00200:101:HGHKYBBXX:2:1101:7182:1701
  read pos         0-44
  score            6
  overlap          10
  errors           2
  error threshold  2
  remaining read   TTGAAAGGTAAGAAAACTGAAAAAGTAGACATGC
  remaining qual   -FFJJJJJJJJJJJJJAJJJJJJJJJJJJFJJJF

  Alignment:

      0     .    :    .    :    .    :    .    :    .    : 
        TTGAAAGGTAAGAAAACTGAAAAAGTAGACATGCAGATGGGAGG------
                                          |||| ||| |      
        ----------------------------------AGATCGGAAGAGCACA

     50     .    :    .    
        ------------------
                          
        CGTCTGAACTCCAGTCAC
`

**Comment by CDieterich** [comment]
Sorry, my fault ..

Ns are counted with +1 in an alignment.

**Comment by jtroehr** [comment]
Right, the alignment output does not display the | symbol for Ns. Nevertheless, these positions are counted as match in the alignment correctly.
