### ISSUE TITLE
Flexbar does not demultiplex reads with default options

### ISSUE THREAD

**Issue by gligong** [seqan/flexbar#12]
Hi:

I am trying to demultiplex Oxford Nanopore MinIon reads with Flexbar v3.0.3. 
When I ran: flexbar -r ont.fastq -b Barcode.fasta, I got 2 remaining reads (demultiplexed).
When I ran: flexbar -r ont.fastq -b Barcode.fasta -bt 0.2, I got 159  remaining reads (demultiplexed).
When I ran: flexbar -r ont.fastq -b Barcode.fasta -bt 0.3 , I got  5,509 remaining reads (demultiplexed).
When I ran: flexbar -r ont.fastq -b Barcode.fasta -bt 0.4 , I got  23,653 remaining reads (demultiplexed).
With a Perl script, I am able to find 9,791 reads that have barcodes with 0 mismatch. What options should I use to allow 0, 1, 2, or 3 barcode mismatches?  The barcodes are 10 bases long.
Thanks!

George

**Comment by jtroehr** [comment]
Hi George,

To allow 0, 1, 2, or 3 mismatches in case of barcodes with 10 bases length, it should work with option -bt set to 0, 0.1, 0.2, or 0.3 as you tried it. I am not sure what is going wrong.

Are the barcodes located on the left tail of the reads (5' end)?

Best, Johannes
