### ISSUE TITLE
Issue installing from source

### ISSUE THREAD

**Issue by AceM1188** [seqan/flexbar#15]
Hi there,

I've been having trouble installing seqan/flexbar from the source code following the listed instructions. I have no problems decompressing both seqan and flexbar files or moving the seqan/include folder to the flexbar-3.4.0 folder. However, please see the following error:

```
benmuldcomputer:Downloads benmulder$ cd flexbar-3.4.0
benmuldcomputer:flexbar-3.4.0 benmulder$ cmake .
-- Flexbar 64 bit architecture
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/benmulder/Downloads/flexbar-3.4.0
benmuldcomputer:flexbar-3.4.0 benmulder$ make
[ 50%] Building CXX object src/CMakeFiles/flexbar.dir/Flexbar.cpp.o
In file included from /Users/benmulder/Downloads/flexbar-3.4.0/src/Flexbar.cpp:24:
/Users/benmulder/Downloads/flexbar-3.4.0/src/Flexbar.h:15:10: fatal error: 'tbb/pipeline.h' file
      not found
#include <tbb/pipeline.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/flexbar.dir/Flexbar.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/flexbar.dir/all] Error 2
make: *** [all] Error 2
```
Any help would be appreciated for addressing this.

Alternatively, I've tried running `brew install homebrew/core/seqan` or `brew install homebrew/core/flexbar` considering the homebrew/science source migrated officially. However, I receive similar errors for the two such as:

```
Error: No available formula with the name "homebrew/core/seqan" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
```

Any help on this error would be much appreciated. 

Thanks!

**Comment by jtroehr** [comment]
It seems like the tbb library is not available on your system. Please install it before building Flexbar from source. You can use homebrew to install the tbb library: `brew install tbb`

Does that solve your issue?

**Comment by AceM1188** [comment]
Hi @jtroehr, thanks for the quick response. 
I actually thought that was the problem previously, but `tbb` is already installed.

When I execute the following, `brew install tbb` I get the following:

```
Warning: tbb 2018_U5 is already installed and up-to-date
To reinstall 2018_U5, run `brew reinstall tbb`
```

After reinstalling, I still get the same error unfortunately when trying to build from source.

**Comment by jtroehr** [comment]
That is strange, I also use homebrew to have the tbb library available and it works. It seems that your installed tbb which should be `/usr/local/include/tbb` is not found by the compiler due to some reason. Have you tried to run `brew doctor`?

You can also install SeqAn and Flexbar with brew: `brew install brewsci/science/flexbar`
However, this installs a much older version 3.0.3 of Flexbar.

**Comment by jtroehr** [comment]
Another possibility if tbb files are not found per default is to extend the file
`flexbar-3.4.0/CMakeLists.txt` by the following lines:

include_directories( /usr/local/Cellar/tbb/2018_U5/include )
link_directories( /usr/local/Cellar/tbb/2018_U5/lib )

**Comment by ljense** [comment]
Hi there! I don't mean to revive old threads, but I am having exactly this problem as well. The homebrew install of the older version of flexbar and seqan did work, but I'd really prefer to use the most updated version. 

Like AceM1188, I have reinstalled tbb (the 2019_U8 version though, of course) and I still get an identical error message. I have also added the two lines you mentioned to the CMakeLists.txt (with '2019_U8' in place of '2018_U5', though) and this also did not solve the error. Any chance you know what is going on?

Thanks!

**Comment by jtroehr** [comment]
Have you checked ``brew doctor`` and if the paths
``/usr/local/Cellar/tbb/2019_U8/include``
``/usr/local/Cellar/tbb/2019_U8/lib``
are actually available on your system?

Another possibility would be to use Bioconda to install Flexbar 3.5 or the provided binaries.

Kind regards, Johannes

**Comment by kvshams** [comment]
getting the similar error in linux. Installed `tbb` and `tbb-dev` under `conda`
```make
Scanning dependencies of target flexbar
[ 50%] Building CXX object CMakeFiles/flexbar.dir/Flexbar.cpp.o
In file included from /Shams/Tools/flexbar/src/Flexbar.cpp:24:0:
/Shams/Tools/flexbar/src/Flexbar.h:15:10: fatal error: tbb/pipeline.h: No such file or directory
 #include <tbb/pipeline.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/flexbar.dir/build.make:63: CMakeFiles/flexbar.dir/Flexbar.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/flexbar.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by kvshams** [comment]
when installing mac it shows : Followed all the above steps, edited `CMakeLists.txt` for the `tbb` path and still got the @AceM1188 error and updated the same in `src/CMakeLists.txt` and now getting the following error. All this error is on recent dev version
```make
-- Flexbar 64 bit architecture
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/svellari/Tools/flexbar
Scanning dependencies of target flexbar
[ 50%] Building CXX object CMakeFiles/flexbar.dir/Flexbar.cpp.o
In file included from /Users/svellari/Tools/flexbar/src/Flexbar.cpp:24:
/Users/svellari/Tools/flexbar/src/Flexbar.h:20:10: fatal error: 'seqan/basic.h' file not found
#include <seqan/basic.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/flexbar.dir/Flexbar.cpp.o] Error 1
make[1]: *** [CMakeFiles/flexbar.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by pabloyler** [comment]
I got the same original error as @AceM1188. For me it wasn't working (I think) because the current `tbb@2021` no longer has `pipeline.h` but rather `parallel-pipeline.h` ... using `tbb@2020` and extending `CMakeLists.txt` as noted by @jtroehr works fine though.
