### ISSUE TITLE
Flexbar crashes with high number of barcode combinations

### ISSUE THREAD

**Issue by martinclausen2** [seqan/flexbar#16]
Hello Johannes,

Thanks for the nice project!
I have almost 5000 barcode combinations (system with fwd and rev barcodes). Flexbar unfortunately is not able to handle such a high number of files to be open in parallel.
Could this be improved?

Best regards,
Martin

**Comment by martinclausen2** [comment]
Thanks for the quick reply! The messages reads as follows:
ERROR: Could not open file flexbarOut_barcode_myfrwcode-myrevcode_1.fastq
Where myfrwcode and myrevcode are some sequences.
There are at this point 1018 flexbarOut*.fastq files.
I run a Debian 9 inside virtualbox.

Unfortunately I am not allowed to share my files. I can offer to test any development stage of new code.

**Comment by jtroehr** [comment]
Ok, that makes it difficult for me to reproduce that issue. Actually, there is no restriction for the number of barcode combinations and files in Flexbar. So that should not be the problem in my eyes.

Are you sure that it is not a simple issue, like not enough space in your VM or non filename characters in the names of your barcodes? What are the names of myfrwcode and myrevcode barcodes in case of the affected file?

**Comment by martinclausen2** [comment]
Sorry for not being able to share the sequences.

At the time of the crash all files have 0 bytes (not 100% checked). It happens when I use my home folder in the Vm or a mounted folder from the windows host. There is some space available.
I tried with nano the create the file where flexbar fails and it it worked.
For the moment I used the barcode as a barcode name, so the name is just a combination of ACTG

**Comment by cjfields** [comment]
Is this an open file limit issue?  What is your `ulimit -Hn`?

https://www.tecmint.com/increase-set-open-file-limits-in-linux/

**Comment by jtroehr** [comment]
Good point, this is probably an issue with open file limits.

@martinclausen2 Does the above mentioned post solve your issue?

**Comment by martinclausen2** [comment]
Sorry for not responding faster: my open file limit is 1048576, so that should not be the point My issue is not solved so far.

**Comment by jtroehr** [comment]
Thank you for reporting this. I recently tested the issue and Flexbar finished the file creation stage without errors for 5000 and also higher numbers of barcode combinations when the open file limit was high enough. However if the limit was too low I got the same error message that you reported.

Which numbers do you get for:
`cat /proc/sys/fs/file-max`
`ulimit -Sn`
`ulimit -Hn`

Kind regards, Johannes

**Comment by martinclausen2** [comment]
Hi Johannes, you are right, I did use ulimit -n unlimited, which was supposed to change both limits, but the softlimit remained unchanged (and unnoticed by me).  Maybe I rebooted in between the tests. After an additional ulimit -Sn unlimited flexbar works. (well, it is still running ...) Thanks a lot!
Best regards,
Martin
