### ISSUE TITLE
DNA ambiguity characters in primer sequences

### ISSUE THREAD

**Issue by f-heeger** [seqan/flexbar#18]
Since I switched to version 3, if there is an ambiguity character in my primer sequence I get an error like this:
> ERROR: Unexpected character 'W' found. 
 My command is:
> flexbar -n 4 -r all_R1.fastq.gz -p all_R2.fastq.gz -t primers/all -b forward_primer.fasta -b2 reverse_primer.fasta -bk -be LTAIL -bn 25 -bt 0.480000 -u 100 -z GZ

Where forward_primer is:
> \>ITS
> AACCAWCGATGAAGAACGCAG

If I replace the the W with a N it works. I am not sure if this intended, but I think ambiguity characters in primer sequences are a needed feature.

**Comment by jtroehr** [comment]
Thank you for this feature request. I will consider to implement that in a future version of Flexbar.

There were Flexbar versions prior to 3.0 that accepted adapter sequence characters that differ from ATCGN. However, such characters were never treated as DNA ambiguity characters. So even with earlier versions of Flexbar the N character should be used in this case.

Kind regards, Johannes
