### ISSUE TITLE
NextFlex UMI detection

### ISSUE THREAD

**Issue by CDieterich** [seqan/flexbar#25]
Hi Johannes,

I was wondering what settings should be used for Nextflex UMI detection.

Basically, I have 50nt single end reads:

NNNN+seq+NNNN+TGGAATTCTCGGGTGCCAAGG (Illumina small RNA)

Adapter + UMI should be trimmed NNNN+NNNN should appear in the read name.

**Comment by jtroehr** [comment]
As one part of the UMI is not connected to the adapter, Flexbar has to be run twice.

One time to extract the first UMI part on the left side with options:
``--adapter-seq NNNN --adapter-trim-end LTAIL --umi-tags``

And a second time with options:
``--adapter-seq NNNNTGGAATTCTCGGGTGCCAAGG --adapter-trim-end RIGHT --umi-tags``

Does it work like this?

Best wishes, Johannes
