### ISSUE TITLE
Trimming different lengths for R1 and R2?

### ISSUE THREAD

**Issue by yanickpouliot** [seqan/flexbar#3]
Howdy. For paired reads, is there a way of trimming length X for R1 reads, and length Y for R2 reads?

Thx much!

Yannick

**Comment by jtroehr** [comment]
Thanks for your request. Are we talking about parameters x and y (pre-trim-left and pre-trim-right), or k (post-trim-length)? For these options it is currently not possible but I could integrate it. Or do you mean another trimming length?

**Comment by yanickpouliot** [comment]
I mean e.g., trimming length of 12 for R1 reads and trimming length of 5 for R2 reads...

**Comment by jtroehr** [comment]
Still not sure if I get it - do you mean trimming from the end of R1 and R2 reads?
