### ISSUE TITLE
Unexpected end of input.

### ISSUE THREAD

**Issue by HibaLaghrissi** [seqan/flexbar#39]
Hi,

I downloaded flexbar successfully using conda. However, when I run the command line (even the basic one), I get this error 

>flexbar -r dydy3i3g.fastq -a ../adapters.fasta -b ../barcodes.fa 
ERROR: Unexpected end of input.
Program execution aborted.

PS : it works when I do flexbar -h or -hh

**Comment by tony-travis** [comment]
Make sure that your files are Unix/Linux "\n" line-terminated text files, not DOS/Windows "\r\n" format and make sure your files have a "\n" as the last character on the last line in the file (sometimes files get truncated and don't end with a complete line).

**Comment by HibaLaghrissi** [comment]
Thank you a lot for your fast reply. Please, do you know how I can check/corect the end of the file ? samtools view doesn't tell me if the lines end with \n or something else

> Make sure that your files are Unix/Linux "\n" line-terminated text files, not DOS/Windows "\r\n" format and make sure your files have a "\n" as the last character on the last line in the file (sometimes files get truncated and don't end with a complete line).

**Comment by HibaLaghrissi** [comment]
Thank you a lot for your fast reply. Please, do you know how I can check/corect the end of the file ? samtools view doesn't tell me if the lines end with \n or something else

> Make sure that your files are Unix/Linux "\n" line-terminated text files, not DOS/Windows "\r\n" format and make sure your files have a "\n" as the last character on the last line in the file (sometimes files get truncated and don't end with a complete line).

**Comment by tony-travis** [comment]
You could use the "file" command to check:
`file filename`
or pipe the last few lines of the file through "od":
`tail filename | od -c"`

**Comment by HibaLaghrissi** [comment]
Thank you ! It helped 

> You could use the "file" command to check:
> `file filename`
> or pipe the last few lines of the file through "od":
> `tail filename | od -c"`
