### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by tseemann** [seqan/flexbar#5]
It's been > 100 commits since 2.7, it would be great if you could make a new release so I can package it in homebrew-science

**Comment by jtroehr** [comment]
I work on a major release and will tag it as soon as it is complete.

**Comment by tseemann** [comment]
You can always tag a 3.0-beta "pre-release" too. 

But I will wait - I am hoping Flexbar can replace Trimmomatic in my pipelines.
