### ISSUE TITLE
Unable to open bz2 files if wrong prefix

### ISSUE THREAD

**Issue by tjakobi** [seqan/flexbar#6]
flexbar 2.7 is unable to open a valid bz2 read file named library_name.txt.bz2. If the file is renamed library_name.fq.bz2 flexbar runs without issues.

Is there a reason why this check is performed?

**Comment by jtroehr** [comment]
Right, the library that is used for IO requires the standard fasta and fastq extensions.

**Comment by tjakobi** [comment]
Is there no possibility of changing this list of "default" extensions in the library? Files with the extension .txt.[gz|bz2] is what you get from several different sequencing facilities (and, IIRC also from the Illumina machines them self). This change broke our pipelines that handle incoming data and we have to "fix" this by symlinking the original files. Would it be possible to have a short changelog for new versions to document changes like this?

**Comment by jtroehr** [comment]
Thank you for the request. Sorry for the inconvenience caused by the issue with extensions in the library. I will try to make the free choice of extensions possible again in future releases. This would also be helpful to fix the broken Galaxy tool without symlinks.
