### ISSUE TITLE
Galaxy .dat vs required format extension

### ISSUE THREAD

**Issue by scholtalbers** [seqan/flexbar#7]
I'm encountering the same issue as mentioned here: http://dev.list.galaxyproject.org/flexbar-v2-7-amp-required-format-extension-td4669578.html
The tool error in galaxy will just mention: "could not read file".
For now I could just do the suggested symlinking, but possibly this can be solved in the official wrapper or tool (e.g. accepting an additional format argument)?

**Comment by jtroehr** [comment]
Thank you for the hint. We will try to find a solution.

**Comment by jtroehr** [comment]
In Flexbar 3.4 it works again to use the dat extension for fastq input files. I updated the Galaxy tool definition and it is available in the Galaxy tool shed.
